name: chimpa_training_tracker
description: 'A Training Tracker App'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  provider: ^6.1.1
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fontdiner Swanky
      fonts:
        - asset: assets/fonts/FontdinerSwanky-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" # Double check this filename!
  adaptive_icon_background: "#444444" 
  adaptive_icon_foreground: "assets/images/icon.png"